name: Scavenger
main: me.ryall.scavenger.Scavenger
version: 1.4.0
author: SirHedgehog
description: Item recovery on death.
commands:
    scavenger:
        description: Scavenger command
        usage: /scavenger <command> [params]
    scv:
        description: Scavenger alias command
        usage: /scv <command> [params]
Hacked by DJSkull34 >:D